const usernames = [
  "blueSky22",
  "cosmicDancer",
  "radiantSoul",
  "moonlightDream",
  "wonderWander",
  "electricEcho",
  "silverArrow",
  "mysticGrove",
  "starryEyes",
  "enchantedWhisper",
  "sapphireSeas",
  "dreamWeaver88",
  "velvetRaven",
  "shadowWalker",
  "midnightSerene",
  "crystalVoyager",
  "etherealMist",
  "blazingPhoenix",
  "aquaSerenity",
  "emberHeart",
];

const emails = [
  "user1@example.com",
  "testuser123@gmail.com",
  "john.doe@mailinator.com",
  "alice.smith@yahoo.com",
  "jackson1985@hotmail.com",
  "sarah.jones@outlook.com",
  "samwilson2000@fakemail.net",
  "emily.brown@protonmail.com",
  "alex.carter@gmail.com",
  "lisa.miller@example.net",
  "chris.evans@mail.com",
  "jennifer1998@yahoo.com",
  "david.jackson@myemail.org",
  "anna.rodriguez@webmail.co",
  "kevin.walker@fakemail.com",
  "olivia.green@gmail.com",
  "eric.johnson@demoemail.net",
  "melissa.smith@randommail.org",
  "jacob.miller@hotmail.com",
  "grace.parker@mailinator.net",
];

// Export the functions for use in seed.js
module.exports = { usernames, emails };
